# Generated by Django 6.0.5 on 2026-05-28 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETE", "Complete"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "file_hash",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("records_created", models.PositiveIntegerField(default=0)),
                ("records_failed", models.PositiveIntegerField(default=0)),
                ("error_log", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingestion_runs",
                        to="organizations.datasource",
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingestion_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RawRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_row_id", models.CharField(blank=True, max_length=255)),
                ("raw_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ingestion_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_records",
                        to="ingestion.ingestionrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NormalizedRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "original_value",
                    models.DecimalField(decimal_places=6, max_digits=18),
                ),
                ("original_unit", models.CharField(max_length=50)),
                (
                    "normalized_value",
                    models.DecimalField(decimal_places=6, max_digits=18),
                ),
                ("normalized_unit", models.CharField(default="kg_CO2e", max_length=20)),
                (
                    "ghg_scope",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Scope 1 — Direct Combustion"),
                            (2, "Scope 2 — Purchased Electricity"),
                            (3, "Scope 3 — Value Chain"),
                        ]
                    ),
                ),
                ("activity_type", models.CharField(max_length=100)),
                (
                    "emission_factor_used",
                    models.DecimalField(decimal_places=8, max_digits=18),
                ),
                ("emission_factor_source", models.CharField(max_length=100)),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("APPROVED", "Approved"),
                            ("FLAGGED", "Flagged"),
                            ("LOCKED", "Locked"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "raw_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="normalized",
                        to="ingestion.rawrecord",
                    ),
                ),
            ],
        ),
    ]
