[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && gunicorn breathe_esg.wsgi --log-file -"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.healthcheck]
path = "/api/health/"
